### ISSUE TITLE
Support for 11g

### ISSUE THREAD

**Issue by zygimantus** [gyorgyabraham/spring-boot-weblogic-example#1]
Hello, I tried to run this project on WebLogic 11g but it does not work. What should I change that it will work?

**Comment by gyorgyabraham** [comment]
What does exactly you mean by not working? Have you tried POST-ing like I wrote in README.md ?

**Comment by zygimantus** [comment]
Yes, when trying POST-ing a result is like this:
![paveikslas](https://user-images.githubusercontent.com/8781824/35961081-01a5cf7e-0cb5-11e8-9023-1b0b9ad6aada.png)

After changing to `curl -X POST -H "Content-Type: text/xml" --data-binary @request.xml http://localhost:7001/mockservice/` i got this 403 error:
![paveikslas](https://user-images.githubusercontent.com/8781824/35961139-3e5f011a-0cb5-11e8-98ae-2cdc0748968d.png)

**Comment by gyorgyabraham** [comment]
I can verify this bug with 11g. I am locating the errors. However I don't have much time currently, so any help is welcome.

**Comment by dennespm** [comment]
i tried to run mvn clean package but i got

[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb22-plugin:0.13.1:generate (generate) on project weblogic-spring-boot-example: Unable to parse configuration of mojo org.jvnet.jaxb2.maven2:maven-jaxb22-plugin:0.13.1:generate for parameter schemaIncludes: Cannot assign configuration entry 'schemaIncludes' with value 'allSchemas.xsd' of type java.lang.String to property of type java.lang.String[] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException

**Comment by gyorgyabraham** [comment]
hello @dennespm 
what Java version are you using? I think this project supports Java 8.
(you might guess it is abandoned :)
